module.exports = [
  { n: 1,  name: { ar: "سورة الفاتحة", en: "Al-Fatihah" }, ayat: 7 },
  { n: 2,  name: { ar: "سورة البقرة", en: "Al-Baqarah" }, ayat: 286 },
  { n: 3,  name: { ar: "سورة آل عمران", en: "Aal-E-Imran" }, ayat: 200 },
  { n: 4,  name: { ar: "سورة النساء", en: "An-Nisa" }, ayat: 176 },
  { n: 5,  name: { ar: "سورة المائدة", en: "Al-Ma'idah" }, ayat: 120 },
  { n: 6,  name: { ar: "سورة الأنعام", en: "Al-An'am" }, ayat: 165 },
  { n: 7,  name: { ar: "سورة الأعراف", en: "Al-A'raf" }, ayat: 206 },
  { n: 8,  name: { ar: "سورة الأنفال", en: "Al-Anfal" }, ayat: 75 },
  { n: 9,  name: { ar: "سورة التوبة", en: "At-Tawbah" }, ayat: 129 },
  { n: 10, name: { ar: "سورة يونس", en: "Yunus" }, ayat: 109 },
  { n: 11, name: { ar: "سورة هود", en: "Hud" }, ayat: 123 },
  { n: 12, name: { ar: "سورة يوسف", en: "Yusuf" }, ayat: 111 },
  { n: 13, name: { ar: "سورة الرعد", en: "Ar-Ra'd" }, ayat: 43 },
  { n: 14, name: { ar: "سورة إبراهيم", en: "Ibrahim" }, ayat: 52 },
  { n: 15, name: { ar: "سورة الحجر", en: "Al-Hijr" }, ayat: 99 },
  { n: 16, name: { ar: "سورة النحل", en: "An-Nahl" }, ayat: 128 },
  { n: 17, name: { ar: "سورة الإسراء", en: "Al-Isra" }, ayat: 111 },
  { n: 18, name: { ar: "سورة الكهف", en: "Al-Kahf" }, ayat: 110 },
  { n: 19, name: { ar: "سورة مريم", en: "Maryam" }, ayat: 98 },
  { n: 20, name: { ar: "سورة طه", en: "Ta-Ha" }, ayat: 135 },
  { n: 21, name: { ar: "سورة الأنبياء", en: "Al-Anbiya" }, ayat: 112 },
  { n: 22, name: { ar: "سورة الحج", en: "Al-Hajj" }, ayat: 78 },
  { n: 23, name: { ar: "سورة المؤمنون", en: "Al-Mu'minun" }, ayat: 118 },
  { n: 24, name: { ar: "سورة النور", en: "An-Nur" }, ayat: 64 },
  { n: 25, name: { ar: "سورة الفرقان", en: "Al-Furqan" }, ayat: 77 },
  { n: 26, name: { ar: "سورة الشعراء", en: "Ash-Shu'ara" }, ayat: 227 },
  { n: 27, name: { ar: "سورة النمل", en: "An-Naml" }, ayat: 93 },
  { n: 28, name: { ar: "سورة القصص", en: "Al-Qasas" }, ayat: 88 },
  { n: 29, name: { ar: "سورة العنكبوت", en: "Al-Ankabut" }, ayat: 69 },
  { n: 30, name: { ar: "سورة الروم", en: "Ar-Rum" }, ayat: 60 },

  // 🔹 من هنا للنهاية نفس النمط (محول بالكامل)
  { n: 31, name: { ar: "سورة لقمان", en: "Luqman" }, ayat: 34 },
  { n: 32, name: { ar: "سورة السجدة", en: "As-Sajdah" }, ayat: 30 },
  { n: 33, name: { ar: "سورة الأحزاب", en: "Al-Ahzab" }, ayat: 73 },
  { n: 34, name: { ar: "سورة سبأ", en: "Saba" }, ayat: 54 },
  { n: 35, name: { ar: "سورة فاطر", en: "Fatir" }, ayat: 45 },
  { n: 36, name: { ar: "سورة يس", en: "Ya-Sin" }, ayat: 83 },
  { n: 37, name: { ar: "سورة الصافات", en: "As-Saffat" }, ayat: 182 },
  { n: 38, name: { ar: "سورة ص", en: "Sad" }, ayat: 88 },
  { n: 39, name: { ar: "سورة الزمر", en: "Az-Zumar" }, ayat: 75 },
  { n: 40, name: { ar: "سورة غافر", en: "Ghafir" }, ayat: 85 },

  { n: 41, name: { ar: "سورة فصلت", en: "Fussilat" }, ayat: 54 },
  { n: 42, name: { ar: "سورة الشورى", en: "Ash-Shura" }, ayat: 53 },
  { n: 43, name: { ar: "سورة الزخرف", en: "Az-Zukhruf" }, ayat: 89 },
  { n: 44, name: { ar: "سورة الدخان", en: "Ad-Dukhan" }, ayat: 59 },
  { n: 45, name: { ar: "سورة الجاثية", en: "Al-Jathiyah" }, ayat: 37 },

  { n: 46, name: { ar: "سورة الأحقاف", en: "Al-Ahqaf" }, ayat: 35 },
  { n: 47, name: { ar: "سورة محمد", en: "Muhammad" }, ayat: 38 },
  { n: 48, name: { ar: "سورة الفتح", en: "Al-Fath" }, ayat: 29 },
  { n: 49, name: { ar: "سورة الحجرات", en: "Al-Hujurat" }, ayat: 18 },
  { n: 50, name: { ar: "سورة ق", en: "Qaf" }, ayat: 45 },

  { n: 51, name: { ar: "سورة الذاريات", en: "Adh-Dhariyat" }, ayat: 60 },
  { n: 52, name: { ar: "سورة الطور", en: "At-Tur" }, ayat: 49 },
  { n: 53, name: { ar: "سورة النجم", en: "An-Najm" }, ayat: 62 },
  { n: 54, name: { ar: "سورة القمر", en: "Al-Qamar" }, ayat: 55 },
  { n: 55, name: { ar: "سورة الرحمن", en: "Ar-Rahman" }, ayat: 78 },

  { n: 56, name: { ar: "سورة الواقعة", en: "Al-Waqi'ah" }, ayat: 96 },
  { n: 57, name: { ar: "سورة الحديد", en: "Al-Hadid" }, ayat: 29 },
  { n: 58, name: { ar: "سورة المجادلة", en: "Al-Mujadila" }, ayat: 22 },
  { n: 59, name: { ar: "سورة الحشر", en: "Al-Hashr" }, ayat: 24 },
  { n: 60, name: { ar: "سورة الممتحنة", en: "Al-Mumtahanah" }, ayat: 13 },

  { n: 61, name: { ar: "سورة الصف", en: "As-Saff" }, ayat: 14 },
  { n: 62, name: { ar: "سورة الجمعة", en: "Al-Jumu'ah" }, ayat: 11 },
  { n: 63, name: { ar: "سورة المنافقون", en: "Al-Munafiqun" }, ayat: 11 },
  { n: 64, name: { ar: "سورة التغابن", en: "At-Taghabun" }, ayat: 18 },
  { n: 65, name: { ar: "سورة الطلاق", en: "At-Talaq" }, ayat: 12 },

  { n: 66, name: { ar: "سورة التحريم", en: "At-Tahrim" }, ayat: 12 },
  { n: 67, name: { ar: "سورة الملك", en: "Al-Mulk" }, ayat: 30 },
  { n: 68, name: { ar: "سورة القلم", en: "Al-Qalam" }, ayat: 52 },
  { n: 69, name: { ar: "سورة الحاقة", en: "Al-Haqqah" }, ayat: 52 },
  { n: 70, name: { ar: "سورة المعارج", en: "Al-Ma'arij" }, ayat: 44 },

  { n: 71, name: { ar: "سورة نوح", en: "Nuh" }, ayat: 28 },
  { n: 72, name: { ar: "سورة الجن", en: "Al-Jinn" }, ayat: 28 },
  { n: 73, name: { ar: "سورة المزمل", en: "Al-Muzzammil" }, ayat: 20 },
  { n: 74, name: { ar: "سورة المدثر", en: "Al-Muddaththir" }, ayat: 56 },
  { n: 75, name: { ar: "سورة القيامة", en: "Al-Qiyamah" }, ayat: 40 },

  { n: 76, name: { ar: "سورة الإنسان", en: "Al-Insan" }, ayat: 31 },
  { n: 77, name: { ar: "سورة المرسلات", en: "Al-Mursalat" }, ayat: 50 },
  { n: 78, name: { ar: "سورة النبأ", en: "An-Naba" }, ayat: 40 },
  { n: 79, name: { ar: "سورة النازعات", en: "An-Nazi'at" }, ayat: 46 },
  { n: 80, name: { ar: "سورة عبس", en: "Abasa" }, ayat: 42 },

  { n: 81, name: { ar: "سورة التكوير", en: "At-Takwir" }, ayat: 29 },
  { n: 82, name: { ar: "سورة الإنفطار", en: "Al-Infitar" }, ayat: 19 },
  { n: 83, name: { ar: "سورة المطففين", en: "Al-Mutaffifin" }, ayat: 36 },
  { n: 84, name: { ar: "سورة الإنشقاق", en: "Al-Inshiqaq" }, ayat: 25 },
  { n: 85, name: { ar: "سورة البروج", en: "Al-Buruj" }, ayat: 22 },

  { n: 86, name: { ar: "سورة الطارق", en: "At-Tariq" }, ayat: 17 },
  { n: 87, name: { ar: "سورة الأعلى", en: "Al-A'la" }, ayat: 19 },
  { n: 88, name: { ar: "سورة الغاشية", en: "Al-Ghashiyah" }, ayat: 26 },
  { n: 89, name: { ar: "سورة الفجر", en: "Al-Fajr" }, ayat: 30 },
  { n: 90, name: { ar: "سورة البلد", en: "Al-Balad" }, ayat: 20 },

  { n: 91, name: { ar: "سورة الشمس", en: "Ash-Shams" }, ayat: 15 },
  { n: 92, name: { ar: "سورة الليل", en: "Al-Layl" }, ayat: 21 },
  { n: 93, name: { ar: "سورة الضحى", en: "Ad-Duha" }, ayat: 11 },
  { n: 94, name: { ar: "سورة الشرح", en: "Ash-Sharh" }, ayat: 8 },
  { n: 95, name: { ar: "سورة التين", en: "At-Tin" }, ayat: 8 },

  { n: 96, name: { ar: "سورة العلق", en: "Al-Alaq" }, ayat: 19 },
  { n: 97, name: { ar: "سورة القدر", en: "Al-Qadr" }, ayat: 5 },
  { n: 98, name: { ar: "سورة البينة", en: "Al-Bayyinah" }, ayat: 8 },
  { n: 99, name: { ar: "سورة الزلزلة", en: "Az-Zalzalah" }, ayat: 8 },
  { n: 100, name: { ar: "سورة العاديات", en: "Al-Adiyat" }, ayat: 11 },

  { n: 101, name: { ar: "سورة القارعة", en: "Al-Qari'ah" }, ayat: 11 },
  { n: 102, name: { ar: "سورة التكاثر", en: "At-Takathur" }, ayat: 8 },
  { n: 103, name: { ar: "سورة العصر", en: "Al-Asr" }, ayat: 3 },
  { n: 104, name: { ar: "سورة الهمزة", en: "Al-Humazah" }, ayat: 9 },
  { n: 105, name: { ar: "سورة الفيل", en: "Al-Fil" }, ayat: 5 },

  { n: 106, name: { ar: "سورة قريش", en: "Quraysh" }, ayat: 4 },
  { n: 107, name: { ar: "سورة الماعون", en: "Al-Ma'un" }, ayat: 7 },
  { n: 108, name: { ar: "سورة الكوثر", en: "Al-Kawthar" }, ayat: 3 },
  { n: 109, name: { ar: "سورة الكافرون", en: "Al-Kafirun" }, ayat: 6 },
  { n: 110, name: { ar: "سورة النصر", en: "An-Nasr" }, ayat: 3 },

  { n: 111, name: { ar: "سورة المسد", en: "Al-Masad" }, ayat: 5 },
  { n: 112, name: { ar: "سورة الإخلاص", en: "Al-Ikhlas" }, ayat: 4 },
  { n: 113, name: { ar: "سورة الفلق", en: "Al-Falaq" }, ayat: 5 },
  { n: 114, name: { ar: "سورة الناس", en: "An-Nas" }, ayat: 6 }
];