const mumaker = require('mumaker');
const { getLang } = require('../../lib/lang');

// Command: textmaker
// AR: إنشاء صورة نص بتأثيرات جاهزة (اختار type + اكتب text)
// EN: Generate styled text image (choose type + provide text)

function getTXT(lang = 'en') {
  const TXT = {
    en: {
      usage:
        '✨ TextMaker\n\nUse:\n.textmaker <type> <text>\n\nExample:\n.textmaker metallic Nick\n\nTypes:\nmetallic, ice, snow, impressive, matrix, light, neon, devil, purple, thunder, leaves, 1917, arena, hacker, sand, blackpink, glitch, fire',
      needText: '❌ Please provide text.\nExample: .textmaker metallic Nick',
      needType: '❌ Please provide a type.\nExample: .textmaker neon EasyStep',
      invalidType: '❌ Invalid type. Use: .textmaker to see the list.',
      processing: '✨ Generating your design... please wait.',
      fail: '❌ Failed to generate design. Try again later.',
      caption: '✨ GENERATED BY EASYSTEP-BOT'
    },
    ar: {
      usage:
        '✨ صانع النصوص\n\nالاستخدام:\n.textmaker <النوع> <النص>\n\nمثال:\n.textmaker metallic Nick\n\nالأنواع:\nmetallic, ice, snow, impressive, matrix, light, neon, devil, purple, thunder, leaves, 1917, arena, hacker, sand, blackpink, glitch, fire',
      needText: '❌ اكتب النص.\nمثال: .textmaker metallic Nick',
      needType: '❌ اكتب نوع التأثير.\nمثال: .textmaker neon EasyStep',
      invalidType: '❌ نوع التأثير غير صحيح. اكتب .textmaker علشان تشوف الأنواع.',
      processing: '✨ جاري إنشاء التصميم... استنى شوية.',
      fail: '❌ فشل إنشاء التصميم.. جرّب تاني بعد شوية.',
      caption: '✨ تم الإنشاء بواسطة EasyStep-Bot'
    }
  };
  return TXT[lang] || TXT.en;
}

const EFFECTS = {
  metallic: 'https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html',
  ice: 'https://en.ephoto360.com/ice-text-effect-online-101.html',
  snow: 'https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html',
  impressive: 'https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html',
  matrix: 'https://en.ephoto360.com/matrix-text-effect-154.html',
  light: 'https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html',
  neon: 'https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html',
  devil: 'https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html',
  purple: 'https://en.ephoto360.com/purple-text-effect-online-100.html',
  thunder: 'https://en.ephoto360.com/thunder-text-effect-online-97.html',
  leaves: 'https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html',
  '1917': 'https://en.ephoto360.com/1917-style-text-effect-523.html',
  arena: 'https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html',
  hacker: 'https://en.ephoto360.com/create-anonymous-hacker-avatars-cyan-neon-677.html',
  sand: 'https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html',
  blackpink: 'https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html',
  glitch: 'https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html',
  fire: 'https://en.ephoto360.com/flame-lettering-effect-372.html'
};

async function textmakerCommand(sock, message, args = []) {
  const chatId = message.key.remoteJid;
  const lang = getLang(chatId);
  const T = getTXT(lang);

  try {
    // no args -> show usage
    if (!Array.isArray(args) || args.length === 0) {
      await sock.sendMessage(chatId, { text: T.usage }, { quoted: message });
      return;
    }

    const type = String(args[0] || '').toLowerCase().trim();
    const text = args.slice(1).join(' ').trim();

    if (!type) {
      await sock.sendMessage(chatId, { text: T.needType }, { quoted: message });
      return;
    }

    if (!text) {
      await sock.sendMessage(chatId, { text: T.needText }, { quoted: message });
      return;
    }

    const url = EFFECTS[type];
    if (!url) {
      await sock.sendMessage(chatId, { text: T.invalidType }, { quoted: message });
      return;
    }

    // processing
    try {
      await sock.sendMessage(chatId, { text: T.processing }, { quoted: message });
    } catch {}

    const result = await mumaker.ephoto(url, text);

    if (!result || !result.image) throw new Error('No image returned');

    await sock.sendMessage(
      chatId,
      { image: { url: result.image }, caption: T.caption },
      { quoted: message }
    );
  } catch (err) {
    console.error('[TEXTMAKER] error:', err?.message || err);
    await sock.sendMessage(chatId, { text: (getTXT(getLang(chatId)) || getTXT('en')).fail }, { quoted: message });
  }
}

module.exports = {
  name: 'textmaker',
  aliases: ['textmaker', 'txt', 'logo', 'text', 'تصميم', 'لوجو', 'كتابة', 'زخرفة'],
  category: {
    ar: '🎨 أوامر الصور والستيكر',
    en: '🎨 Image & Sticker Commands'
  },

  description: {
    ar: 'إنشاء صورة نص بتأثيرات جاهزة (type + text).',
    en: 'Generate a styled text image (type + text).'
  },
  usage: {
    ar: '.textmaker <type> <text>',
    en: '.textmaker <type> <text>'
  },
emoji: '✨📝',
  admin: false,
  owner: false,
  showInMenu: true,

  exec: textmakerCommand,
  run: textmakerCommand,
  execute: textmakerCommand
};